apiVersion: apps/v1
kind: Deployment
metadata:
  name: pma-deployment
spec:
  selector:
    matchLabels:
      app: pma
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - name: pma
        imagePullPolicy: Never
        image: pma-server
        ports:
        - 
          name: "pma-http"
          containerPort: 80
        # command: ["nginx", "-g", "daemon off;"]
---
apiVersion: v1
kind: Service
metadata:
  name: pma-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: pma
  ports:
      - name: "http"
        protocol: TCP
        port: 5000
        targetPort: 80
  type: LoadBalancer